language: node_js
node_js:
  - "10"
script:
  - echo 'nothing to build.'

deploy:
  provider: npm
  email: flw_dream@126.com
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true
